from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, Date, DateTime, Float, Integer, String

from .database import Base


def _today():
    return datetime.now(timezone.utc).date()


class Expense(Base):
    __tablename__ = "expenses"

    id = Column(Integer, primary_key=True, index=True)
    description = Column(String(200), nullable=False, default="")
    amount = Column(Float, nullable=False)
    category = Column(String(50), nullable=False, index=True)
    # User-facing transaction date (what monthly grouping/filtering uses) -
    # distinct from created_at, which is just when the row was inserted.
    date = Column(Date, nullable=False, default=_today, index=True)
    # Set when this row was auto-generated by a RecurringEntry template.
    # Not a DB-level foreign key on purpose - deleting a template must not
    # cascade-delete the real transactions it already created.
    recurring_id = Column(Integer, nullable=True, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class Income(Base):
    __tablename__ = "income"

    id = Column(Integer, primary_key=True, index=True)
    description = Column(String(200), nullable=False, default="")
    amount = Column(Float, nullable=False)
    source = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, default=_today, index=True)
    recurring_id = Column(Integer, nullable=True, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class BudgetSettings(Base):
    """Single-row table holding the household's recurring monthly targets.

    There's always exactly one row (created on first read/write by the API
    layer, not enforced at the schema level - simplest option for a single
    config record with no multi-tenancy).
    """

    __tablename__ = "budget_settings"

    id = Column(Integer, primary_key=True, index=True)
    monthly_savings_goal = Column(Float, nullable=False, default=0.0)
    monthly_spending_limit = Column(Float, nullable=False, default=0.0)


class RecurringEntry(Base):
    """A template that auto-generates a real Expense/Income row each month."""

    __tablename__ = "recurring_entries"

    id = Column(Integer, primary_key=True, index=True)
    type = Column(String(10), nullable=False)
    description = Column(String(200), nullable=False, default="")
    amount = Column(Float, nullable=False)
    category = Column(String(50), nullable=True)
    source = Column(String(20), nullable=True)
    day_of_month = Column(Integer, nullable=False)
    active = Column(Boolean, nullable=False, default=True)
    # A subscription is just a recurring expense flagged for the dedicated
    # Subscriptions view/totals - it doesn't change generation behavior.
    is_subscription = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class Account(Base):
    """A manually-entered asset or liability used for net worth tracking."""

    __tablename__ = "accounts"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    type = Column(String(10), nullable=False)
    # Always stored as a positive number - liabilities are subtracted (not
    # negated) when computing net worth.
    balance = Column(Float, nullable=False, default=0.0)
    category = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
