import secrets
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, Date, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from .database import Base


def _today():
    return datetime.now(timezone.utc).date()


class Household(Base):
    __tablename__ = "households"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False)
    invite_code = Column(String(20), unique=True, index=True, nullable=False, default=lambda: secrets.token_urlsafe(8))
    created_by = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    display_name = Column(String(100), nullable=False, default="")
    household_id = Column(Integer, ForeignKey("households.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    household = relationship("Household", foreign_keys=[household_id], backref="members")


class Expense(Base):
    __tablename__ = "expenses"

    id = Column(Integer, primary_key=True, index=True)
    description = Column(String(200), nullable=False, default="")
    amount = Column(Float, nullable=False)
    category = Column(String(50), nullable=False, index=True)
    # User-facing transaction date (what monthly grouping/filtering uses) -
    # distinct from created_at, which is just when the row was inserted.
    date = Column(Date, nullable=False, default=_today, index=True)
    # Set when this row was auto-generated by a RecurringEntry template.
    recurring_id = Column(Integer, nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    household_id = Column(Integer, ForeignKey("households.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class Income(Base):
    __tablename__ = "income"

    id = Column(Integer, primary_key=True, index=True)
    description = Column(String(200), nullable=False, default="")
    amount = Column(Float, nullable=False)
    source = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, default=_today, index=True)
    recurring_id = Column(Integer, nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    household_id = Column(Integer, ForeignKey("households.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class BudgetSettings(Base):
    """Single-row table holding the monthly targets."""

    __tablename__ = "budget_settings"

    id = Column(Integer, primary_key=True, index=True)
    monthly_savings_goal = Column(Float, nullable=False, default=0.0)
    monthly_spending_limit = Column(Float, nullable=False, default=0.0)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    household_id = Column(Integer, ForeignKey("households.id"), nullable=True, index=True)


class RecurringEntry(Base):
    """A template that auto-generates a real Expense/Income row each month."""

    __tablename__ = "recurring_entries"

    id = Column(Integer, primary_key=True, index=True)
    type = Column(String(10), nullable=False)
    description = Column(String(200), nullable=False, default="")
    amount = Column(Float, nullable=False)
    category = Column(String(50), nullable=True)
    source = Column(String(20), nullable=True)
    day_of_month = Column(Integer, nullable=False)
    active = Column(Boolean, nullable=False, default=True)
    is_subscription = Column(Boolean, nullable=False, default=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    household_id = Column(Integer, ForeignKey("households.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class Account(Base):
    """A manually-entered asset or liability used for net worth tracking."""

    __tablename__ = "accounts"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    type = Column(String(10), nullable=False)
    # Always stored as a positive number - liabilities are subtracted when computing net worth.
    balance = Column(Float, nullable=False, default=0.0)
    category = Column(String(50), nullable=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    household_id = Column(Integer, ForeignKey("households.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
